/* 
  GitHub Hosting Adapter 
  Auto-generated by AntiGravity
*/

// CONFIGURATION
// msg: Replace with your deployed Web App URL (executing as 'Me', access 'Anyone')
const BACKEND_URL = 'YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL';

// Polyfill google.script.run if not present
if (typeof google === 'undefined') {
    console.log("Initializing GAS Polyfill for GitHub Hosting");

    class GasRunner {
        constructor() {
            this._success = null;
            this._failure = null;
        }
        withSuccessHandler(cb) {
            this._success = cb;
            return this;
        }
        withFailureHandler(cb) {
            this._failure = cb;
            return this;
        }
    }

    const runnerHandler = {
        get: function (target, prop) {
            if (prop in target) return target[prop]; // withSuccessHandler etc.

            return function (...args) {
                if (BACKEND_URL.includes('YOUR_')) {
                    alert("Backend URL not configured in app.js. Please edit lines 5-6.");
                    console.error("Missing BACKEND_URL");
                    return;
                }

                // Simple POST to GAS doPOST
                fetch(BACKEND_URL, {
                    method: 'POST',
                    body: JSON.stringify({ func: prop, args: args })
                })
                    .then(r => r.json())
                    .then(data => {
                        if (data.success) {
                            if (target._success) target._success(data.response);
                        } else {
                            if (target._failure) target._failure(new Error(data.error));
                        }
                    })
                    .catch(e => {
                        if (target._failure) target._failure(e);
                    });
            };
        }
    };

    // Define google.script.run as a getter to return a fresh runner each time
    window.google = { script: {} };
    Object.defineProperty(window.google.script, 'run', {
        get: () => new Proxy(new GasRunner(), runnerHandler)
    });
}

// --- APP CODE STARTS HERE ---
// App Namespace
const app = {
    state: {
        currentUser: null,
        compressedImage: null,
        isAdminMode: false,
        adminToken: null,
        currencySymbol: '₹' // Default
    },

    init: function () {
        // 1. Setup Defaults (Always run this)
        this.initTheme();
        this.initCurrency();
        this.loadCategories();
        document.getElementById('expense-date').valueAsDate = new Date();
        const today = new Date();
        const firstDay = new Date(today.getFullYear(), today.getMonth(), 1);
        document.getElementById('dash-start').valueAsDate = firstDay;
        document.getElementById('dash-end').valueAsDate = today;

        // 2. Restore Session (Driver or Admin?)
        // Admin Session
        const adminToken = localStorage.getItem('admin_token');
        if (adminToken) {
            this.state.adminToken = adminToken;
            this.state.isAdminMode = true;
            this.showToast('Welcome back, Admin', 'success');
            this.loadAdminDashboard();
            this.showView('admin-view');
            document.querySelector('.bottom-nav').style.display = 'none';
            return;
        }

        // Driver Session
        const savedUser = localStorage.getItem('driver_user');
        if (savedUser) {
            try {
                const user = JSON.parse(savedUser);
                this.state.currentUser = user.id;
                this.state.currentName = user.name;
                this.state.currentVehicle = user.vehicle;

                document.getElementById('hidden-driver-id').value = user.id;

                // Delay slightly to ensure View is ready? No, should be fine.
                this.showToast(`Welcome back, ${user.name}`, 'success');
                this.showView('expense-view');
                // Pre-load dashboard if they were there? No, default to expense view is safer.
            } catch (e) {
                localStorage.removeItem('driver_user');
            }
        }
    },

    // ... existing loadCategories ...
    loadCategories: function () {
        const select = document.getElementById('expense-category');
        if (!select) return; // Safety
        select.innerHTML = '<option value="" disabled selected>Loading...</option>';

        google.script.run
            .withSuccessHandler((cats) => {
                select.innerHTML = '<option value="" disabled selected>Select Category</option>';
                if (cats && cats.length > 0) {
                    cats.forEach(c => {
                        const opt = document.createElement('option');
                        const val = String(c).trim();
                        if (val) { opt.value = val; opt.textContent = val; select.appendChild(opt); }
                    });
                } else {
                    ['Fuel', 'Repair', 'Food', 'Toll', 'Other'].forEach(c => {
                        const opt = document.createElement('option');
                        opt.value = c; opt.textContent = c; select.appendChild(opt);
                    });
                }
            })
            .withFailureHandler(err => { select.innerHTML = '<option value="" disabled selected>Error Loading</option>'; })
            .getExpenseCategories();
    },

    /* --- NAVIGATION --- */
    showNav: function (viewId, el) {
        document.querySelectorAll('.bottom-nav .nav-item').forEach(i => i.classList.remove('active'));
        if (el) el.classList.add('active'); // el might be null if called programmatically
        this.showView(viewId);
        if (viewId === 'dashboard-view') { this.loadDashboard(); }
    },

    showView: function (viewId) {
        document.querySelectorAll('.view').forEach(el => el.classList.remove('active'));
        document.getElementById(viewId).classList.add('active');
    },

    /* --- LOGIN LOGIC --- */
    toggleLoginMode: function (e) {
        if (e) e.preventDefault(); // Prevent link jump

        this.state.isAdminMode = !this.state.isAdminMode;
        const isAdm = this.state.isAdminMode;

        // Update UI
        document.querySelector('#login-view h2').textContent = isAdm ? "Admin Login" : "Welcome Back";
        document.querySelector('#login-view p').textContent = isAdm ? "Enter admin credentials." : "Please log in securely to access your dashboard.";

        document.querySelector('#login-id').placeholder = isAdm ? "Username" : "Ex: DRV001";
        document.querySelector('#login-id').previousElementSibling.textContent = isAdm ? "Username" : "Driver ID";

        document.querySelector('#login-pin').placeholder = isAdm ? "Password" : "••••";
        document.querySelector('#login-pin').previousElementSibling.textContent = isAdm ? "Password" : "Secure PIN";
        // document.querySelector('#login-pin').type = "password"; // This line is redundant as type is already password

        // Clear inputs
        const pinInput = document.getElementById('login-pin');
        pinInput.value = '';
        document.getElementById('login-id').value = '';

        document.getElementById('login-mode-text').textContent = isAdm ? "Are you a Driver?" : "Are you an Admin?";
        const link = document.querySelector('#login-mode-text + a');
        if (link) link.textContent = isAdm ? "Switch to Driver" : "Switch to Admin";
    },

    login: function () {
        const id = document.getElementById('login-id').value.trim();
        const pin = document.getElementById('login-pin').value.trim();
        const errorEl = document.getElementById('login-error');

        if (!id || !pin) {
            errorEl.textContent = 'Please enter required credentials.';
            errorEl.style.display = 'block';
            return;
        }

        errorEl.style.display = 'none';
        const btn = document.querySelector('#login-view .btn');
        const originalText = btn.textContent;
        btn.textContent = 'Verifying...';
        btn.disabled = true;

        const handler = google.script.run
            .withSuccessHandler((response) => {
                btn.textContent = originalText;
                btn.disabled = false;
                if (response.success) {
                    if (this.state.isAdminMode) {
                        // ADMIN SUCCESS
                        this.state.adminToken = response.token;
                        localStorage.setItem('admin_token', response.token);
                        this.showToast('Welcome, Admin', 'success');
                        this.showView('admin-view');
                        document.querySelector('.bottom-nav').style.display = 'none'; // Hide nav
                        this.loadAdminDashboard();
                    } else {
                        // DRIVER SUCCESS
                        this.state.currentUser = response.driverId;
                        this.state.currentName = response.driverName;
                        this.state.currentVehicle = response.vehicleId;
                        localStorage.setItem('driver_user', JSON.stringify({
                            id: response.driverId,
                            name: response.driverName,
                            vehicle: response.vehicleId
                        }));
                        document.getElementById('hidden-driver-id').value = response.driverId;
                        document.querySelector('.bottom-nav').style.display = 'flex'; // Ensure nav shown
                        this.showToast(`Welcome, ${response.driverName}`, 'success');
                        this.showView('expense-view');
                    }
                } else {
                    errorEl.textContent = response.message || 'Invalid Credentials';
                    errorEl.style.display = 'block';

                    // Auto-hide login error after 4s for consistency
                    setTimeout(() => {
                        errorEl.style.display = 'none';
                    }, 4000);
                }
            })
            .withFailureHandler((err) => {
                btn.textContent = originalText;
                btn.disabled = false;
                errorEl.textContent = 'Server Error: ' + err.message;
                errorEl.style.display = 'block';
            });

        // Call appropriate function
        if (this.state.isAdminMode) {
            handler.validateAdmin(id, pin);
        } else {
            handler.validateDriver(id, pin);
        }
    },

    logout: function () {
        localStorage.removeItem('driver_user');
        localStorage.removeItem('admin_token'); // Clear Admin Session
        this.state.currentUser = null;
        this.state.currentName = null;
        this.state.currentVehicle = null;
        this.state.isAdminMode = false;
        this.state.adminToken = null;

        document.getElementById('login-id').value = '';
        document.getElementById('login-pin').value = '';
        document.getElementById('expense-form').reset();
        this.resetPreview();

        // Reset Login UI to driver default
        document.querySelector('#login-view h2').textContent = "Welcome Back";
        document.querySelector('#login-view p').textContent = "Please log in securely to access your dashboard.";
        document.querySelector('#login-id').placeholder = "Ex: DRV001";
        document.querySelector('#login-id').previousElementSibling.textContent = "Driver ID";
        document.querySelector('#login-pin').placeholder = "••••";
        document.querySelector('#login-pin').previousElementSibling.textContent = "Secure PIN";
        document.getElementById('login-mode-text').textContent = "Are you an Admin?";
        document.querySelector('#login-mode-text + a').textContent = "Switch to Admin";

        document.querySelector('.bottom-nav').style.display = 'none'; // Hide bottom nav on login screen logic (actually hidden by CSS usually but good safety)
        this.showView('login-view');
    },

    /* --- EXPENSE SUBMISSION --- */
    submitExpense: function (form) {
        if (!this.state.currentUser) {
            this.showToast('Session expired. Please login again.', 'error');
            this.logout();
            return;
        }

        // 1. Client-Side Validation: Future Date Check - REMOVED per user request
        // const dateVal = document.getElementById('expense-date').value;
        // const today = new Date().toISOString().split('T')[0];
        // if (dateVal > today) { ... }

        // Start Loading
        const btn = document.getElementById('submit-btn');
        const btnText = document.getElementById('btn-text');
        const loader = document.getElementById('btn-loader');

        btn.disabled = true;
        btnText.style.display = 'none';
        loader.style.display = 'block';

        // Prepare Data
        const formData = {
            driverId: this.state.currentUser,
            driverName: this.state.currentName,
            vehicleId: this.state.currentVehicle,
            date: form.date.value,
            category: form.category.value,
            description: form.description.value, // New Field
            km: form.km.value,
            amount: form.amount.value,
            image: this.state.compressedImage // Base64 string from canvas
        };


        google.script.run
            .withSuccessHandler((response) => {
                this.resetSubmissionState(btn, btnText, loader);
                if (response.success) {
                    this.showToast('Expense Submitted Successfully!', 'success');
                    form.reset();
                    this.resetPreview();
                    document.getElementById('expense-date').valueAsDate = new Date(); // Reset date to today
                } else {
                    this.showToast('Error: ' + response.message, 'error');
                }
            })
            .withFailureHandler((err) => {
                this.resetSubmissionState(btn, btnText, loader);
                this.showToast('System Error: ' + err.message, 'error');
            })
            .processExpense(formData);
    },

    resetSubmissionState: function (btn, btnText, loader) {
        btn.disabled = false;
        btnText.style.display = 'inline';
        loader.style.display = 'none';
    },

    /* --- IMAGE HANDLING --- */
    handleFileSelect: function (event) {
        const file = event.target.files[0];
        if (!file) return;

        // Valid types
        const validTypes = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'];
        if (!validTypes.includes(file.type)) {
            alert("Please upload an image or PDF.");
            return;
        }

        const reader = new FileReader();

        if (file.type === 'application/pdf') {
            // PDF HANDLING
            reader.onload = (e) => {
                this.state.compressedImage = e.target.result; // Keep raw PDF Data URL

                // PDF Preview UI
                const previewImg = document.getElementById('preview-img');
                previewImg.style.display = 'none';

                const container = document.getElementById('preview-container');
                let pdfPrev = document.getElementById('pdf-preview-icon');
                if (!pdfPrev) {
                    pdfPrev = document.createElement('div');
                    pdfPrev.id = 'pdf-preview-icon';
                    pdfPrev.style.textAlign = 'center';
                    pdfPrev.innerHTML = '<span style="font-size:40px;">📄</span><div style="font-size:12px; margin-top:4px; color:#fff;">PDF Selected</div>';
                    container.appendChild(pdfPrev);
                }
                pdfPrev.style.display = 'block';
                document.querySelector('.upload-hint').style.display = 'none';
            };
            reader.readAsDataURL(file);

        } else {
            // IMAGE HANDLING
            reader.onload = (e) => {
                const img = new Image();
                img.onload = () => {
                    this.compressImage(img);
                };
                img.src = e.target.result;
            };
            reader.readAsDataURL(file);
        }
    },

    compressImage: function (img) {
        // IMPROVED QUALITY: 1600px Max, 0.85 Quality
        const MAX_WIDTH = 1600;
        const MAX_HEIGHT = 1600;
        let width = img.width;
        let height = img.height;

        if (width > height) {
            if (width > MAX_WIDTH) {
                height *= MAX_WIDTH / width;
                width = MAX_WIDTH;
            }
        } else {
            if (height > MAX_HEIGHT) {
                width *= MAX_HEIGHT / height;
                height = MAX_HEIGHT;
            }
        }

        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, width, height);

        // Compress to JPEG 0.85 quality (High Clarity)
        const dataUrl = canvas.toDataURL('image/jpeg', 0.85);

        this.state.compressedImage = dataUrl;

        // Update Preview
        const previewImg = document.getElementById('preview-img');
        previewImg.src = dataUrl;
        previewImg.style.display = 'block';

        // Hide PDF icon if present
        const pdfPrev = document.getElementById('pdf-preview-icon');
        if (pdfPrev) pdfPrev.style.display = 'none';

        document.querySelector('.upload-hint').style.display = 'none';
    },

    resetPreview: function () {
        this.state.compressedImage = null;
        document.getElementById('preview-img').style.display = 'none';
        document.getElementById('preview-img').src = '';

        const pdfPrev = document.getElementById('pdf-preview-icon');
        if (pdfPrev) pdfPrev.style.display = 'none';

        document.querySelector('.upload-hint').style.display = 'block';
    },

    /* --- DASHBOARD --- */
    loadDashboard: function () {
        if (!this.state.currentUser) return;

        const start = document.getElementById('dash-start').value;
        const end = document.getElementById('dash-end').value;
        const tableBody = document.getElementById('dash-table-body');
        const summaryEl = document.getElementById('dash-cat-summary');
        const loader = document.getElementById('dash-loader');

        // Show Loader
        tableBody.innerHTML = '';
        summaryEl.innerHTML = '<div class="center" style="opacity:0.6;">Loading stats...</div>';
        loader.style.display = 'flex';

        google.script.run
            .withSuccessHandler((data) => {
                console.log("Dashboard Data Received:", data); // Debug
                loader.style.display = 'none';
                try {
                    this.renderDashboard(data);
                } catch (e) {
                    alert("Render Error: " + e.message);
                    console.error(e);
                }
            })
            .withFailureHandler((err) => {
                loader.style.display = 'none';
                tableBody.innerHTML = `<tr><td colspan="4" class="center" style="color:red">Error: ${err.message}</td></tr>`;
                summaryEl.innerHTML = '<div style="color:red">Failed to load.</div>';
            })
            .getDriverExpenses(this.state.currentUser, start, end);
    },

    renderDashboard: function (data) {
        try {
            const tableBody = document.getElementById('dash-table-body');
            const totalEl = document.getElementById('dash-total');
            const kmEl = document.getElementById('dash-km');
            const countEl = document.getElementById('dash-count');
            const catSummaryEl = document.getElementById('dash-cat-summary');

            tableBody.innerHTML = '';
            catSummaryEl.innerHTML = '';

            if (!data || data.length === 0) {
                tableBody.innerHTML = '<tr><td colspan="4" class="center" style="padding:24px; opacity:0.6;">No records found.</td></tr>';
                totalEl.textContent = '₹0.00';
                kmEl.textContent = '0';
                countEl.textContent = '0';
                catSummaryEl.innerHTML = '<div style="opacity:0.6; font-style:italic;">No data available.</div>';
                return;
            }

            let total = 0;
            let totalKm = 0;
            let catMap = {};

            data.forEach(item => {
                const amt = parseFloat(item.amount || 0);
                const km = parseFloat(item.km || 0);

                total += amt;
                totalKm += km;

                // Group by Category
                const cat = item.category || 'Other';
                if (!catMap[cat]) catMap[cat] = 0;
                catMap[cat] += amt;

                // Color Code Status
                let badgeClass = 'pending';
                if (item.status === 'Approved') badgeClass = 'approved';
                if (item.status === 'Rejected') badgeClass = 'rejected';

                const tr = document.createElement('tr');

                // Proof Link Logic - Support PDF
                let proofIcon = '';
                if (item.image) {
                    if (item.image.includes('application/pdf')) {
                        proofIcon = `<a href="${item.image}" target="_blank" style="text-decoration:none; margin-left:8px;" title="View PDF">📄</a>`;
                    } else {
                        proofIcon = `<a href="${item.image}" target="_blank" style="text-decoration:none; margin-left:8px;" title="View Proof">🖼️</a>`;
                    }
                }

                tr.innerHTML = `
                    <td style="font-size:12px;">${item.date}</td>
                    <td>
                        <div style="font-weight:500;">
                            ${item.category} ${proofIcon}
                        </div>
                        <div style="font-size:11px; opacity:0.6;">${item.km ? item.km + ' KM • ' : ''} ${item.description || ''}</div>
                    </td>
                    <td style="text-align:right; font-weight:600;">₹${item.amount}</td>
                    <td style="text-align:center;">
                        ${item.status === 'Pending'
                        ? `<button class="btn-secondary" style="padding:4px 8px; font-size:11px;" onclick="app.editExpense('${item.txnId}')" title="Edit">✏️</button>`
                        : (item.status === 'Rejected'
                            ? `<button class="btn-resubmit" onclick="app.editExpense('${item.txnId}')">Resubmit</button>`
                            : `<span style="font-size:10px;" class="badge ${badgeClass}">${item.status}</span>`
                        )
                    }
                    </td>
                    `;
                tableBody.appendChild(tr);
            });

            totalEl.textContent = '₹' + total.toFixed(2);
            kmEl.textContent = totalKm.toLocaleString();
            countEl.textContent = data.length;

            // Render Category Summary
            Object.keys(catMap).sort().forEach(c => {
                const row = document.createElement('div');
                row.className = 'summ-row';
                row.innerHTML = `<span>${c}</span> <b>₹${catMap[c].toFixed(2)}</b>`;
                catSummaryEl.appendChild(row);
            });

            // Store data for local editing
            this.state.dashboardData = data;
        } catch (e) {
            console.error("Dashboard Render Error:", e);
            alert("Dashboard Error: " + e.message);
        }
    },

    editExpense: function (txnId) {
        const item = this.state.dashboardData.find(i => i.txnId === txnId);
        if (!item) return;

        document.getElementById('edit-txn').value = item.txnId;
        document.getElementById('edit-amount').value = item.amount;
        document.getElementById('edit-km').value = item.km || '';
        document.getElementById('edit-desc').value = item.description || '';

        // Clean Image State
        this.state.editImage = null;
        document.getElementById('edit-image').value = '';
        const preview = document.getElementById('edit-img-preview');
        if (preview) preview.style.display = 'none';

        // Date Format helper for input type="date"
        // Expecting dd/mm/yyyy from item.date -> convert to yyyy-mm-dd
        try {
            const parts = item.date.split('/'); // dd, mm, yyyy
            const isoDate = `${parts[2]}-${parts[1]}-${parts[0]}`;
            document.getElementById('edit-date').value = isoDate;
        } catch (e) {
            console.error("Date parse error", e);
        }

        // Populate Categories if needed (cached)
        const catSelect = document.getElementById('edit-category');
        if (catSelect.options.length <= 1) {
            const cats = this.state.categories || ['Fuel', 'Repair', 'Other']; // Fallback
            cats.forEach(c => {
                const opt = document.createElement('option');
                opt.value = c;
                opt.textContent = c;
                catSelect.appendChild(opt);
            });
        }
        catSelect.value = item.category;

        document.getElementById('edit-modal').classList.remove('hidden');
    },

    closeEdit: function () {
        document.getElementById('edit-modal').classList.add('hidden');
    },

    handleEditFile: function (e) {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();

        if (file.type === 'application/pdf') {
            reader.onload = (evt) => {
                this.state.editImage = evt.target.result;
                // PDF Preview for Edit
                const preview = document.querySelector('#edit-img-preview'); // Container
                const img = preview.querySelector('img');
                img.style.display = 'none';

                let pdfIcon = preview.querySelector('.pdf-icon');
                if (!pdfIcon) {
                    pdfIcon = document.createElement('div');
                    pdfIcon.className = 'pdf-icon';
                    pdfIcon.innerHTML = '📄 PDF';
                    pdfIcon.style.cssText = "font-size:12px; text-align:center; padding:10px; color:#fff;";
                    preview.appendChild(pdfIcon);
                }
                pdfIcon.style.display = 'block';
                preview.style.display = 'block';
            };
            reader.readAsDataURL(file);
        } else {
            // Image
            reader.onload = (evt) => {
                const img = new Image();
                img.onload = () => {
                    const canvas = document.createElement('canvas');
                    // IMPROVED EDIT QUALITY
                    let w = img.width, h = img.height;
                    const MAX = 1600;
                    if (w > h) { if (w > MAX) { h *= MAX / w; w = MAX; } }
                    else { if (h > MAX) { w *= MAX / h; h = MAX; } }

                    canvas.width = w; canvas.height = h;
                    canvas.getContext('2d').drawImage(img, 0, 0, w, h);
                    const dataUrl = canvas.toDataURL('image/jpeg', 0.85);

                    this.state.editImage = dataUrl;

                    const preview = document.getElementById('edit-img-preview');
                    const previewImg = preview.querySelector('img');
                    previewImg.src = dataUrl;
                    previewImg.style.display = 'block';

                    const pdfIcon = preview.querySelector('.pdf-icon');
                    if (pdfIcon) pdfIcon.style.display = 'none';

                    preview.style.display = 'block';
                };
                img.src = evt.target.result;
            }
            reader.readAsDataURL(file);
        }
    },

    saveEdit: function () {
        const txnId = document.getElementById('edit-txn').value;
        const btn = document.querySelector('#edit-modal button[type="submit"]');
        const oldText = btn.textContent;
        btn.textContent = 'Saving...';
        btn.disabled = true;

        const newData = {
            date: document.getElementById('edit-date').value, // yyyy-mm-dd
            category: document.getElementById('edit-category').value,
            amount: document.getElementById('edit-amount').value,
            km: document.getElementById('edit-km').value,
            description: document.getElementById('edit-desc').value,
            image: this.state.editImage // Include Image if uploaded
        };

        // Convert yyyy-mm-dd back to dd/mm/yyyy for consistency/sheet
        const parts = newData.date.split('-');
        const formattedDate = `${parts[2]}/${parts[1]}/${parts[0]}`;
        newData.date = formattedDate;

        // CALLBACK HANDLER
        const handleRes = (res) => {
            btn.textContent = oldText;
            btn.disabled = false;
            if (res.success) {
                this.showToast('Updated successfully', 'success');
                this.closeEdit();
                // Reload appropriate view
                if (this.state.isAdminMode) {
                    this.loadAdminDashboard();
                } else {
                    this.loadDashboard();
                }
            } else {
                this.showToast(res.message, 'error');
            }
        };

        const handleErr = (err) => {
            btn.textContent = oldText;
            btn.disabled = false;
            this.showToast("Error: " + err, 'error');
        };

        // BRANCH LOGIC
        // If Admin Mode, use the Admin Override Function
        if (this.state.isAdminMode) {
            google.script.run
                .withSuccessHandler(handleRes)
                .withFailureHandler(handleErr)
                .updateExpenseAdmin(txnId, newData);
        } else {
            // Normal Driver Logic (Strict Lock)
            google.script.run
                .withSuccessHandler(handleRes)
                .withFailureHandler(handleErr)
                .updateDriverExpense(txnId, newData);
        }
    },

    getIcon: function (cat) {
        const c = String(cat).toLowerCase();
        if (c.includes('fuel') || c.includes('diesel') || c.includes('petrol')) return '⛽';
        if (c.includes('repair') || c.includes('maintenance') || c.includes('service')) return '🔧';
        if (c.includes('food') || c.includes('meal')) return '🍔';
        if (c.includes('toll') || c.includes('parking')) return '🚧';
        if (c.includes('hotel') || c.includes('stay')) return '🏨';
        return '🧾';
    },

    exportPdf: function () {
        const btn = document.querySelector('.btn-export') || document.querySelector('#dashboard-view .btn:not(.btn-secondary)');
        if (!btn) return;

        const oldText = btn.textContent;
        btn.textContent = 'Generating PDF...';
        btn.disabled = true;

        try {
            // 1. Prepare Data
            const data = this.state.dashboardData || [];
            const driverName = this.state.currentUser || "Driver";
            const start = document.getElementById('dash-start').value || 'Start';
            const end = document.getElementById('dash-end').value || 'End';

            // 2. Populate Template
            document.getElementById('pdf-driver-name').textContent = driverName;
            document.getElementById('pdf-period').textContent = `Period: ${start} to ${end}`;
            document.getElementById('pdf-gen-date').textContent = "Generated: " + new Date().toLocaleDateString();

            // Totals
            let total = 0;
            let km = 0;
            data.forEach(x => {
                total += parseFloat(x.amount || 0);
                km += parseFloat(x.km || 0);
            });

            document.getElementById('pdf-total-amt').textContent = '₹' + total.toFixed(2);
            document.getElementById('pdf-total-km').textContent = km.toLocaleString() + ' KM';
            document.getElementById('pdf-total-trips').textContent = data.length;

            // List
            const listContainer = document.getElementById('pdf-list-container');
            listContainer.innerHTML = '';

            if (data.length === 0) {
                listContainer.innerHTML = '<div style="padding:20px; text-align:center; color:#999;">No records found for this period.</div>';
            } else {
                data.forEach(item => {
                    const div = document.createElement('div');
                    div.style.cssText = "display:grid; grid-template-columns: 2fr 3fr 2fr 2fr; padding:12px 15px; border-bottom:1px solid #eee; font-size:12px; align-items:center;";

                    const statusColor = item.status === 'Approved' ? '#166534' : (item.status === 'Rejected' ? '#991B1B' : '#92400E');
                    const statusBg = item.status === 'Approved' ? '#DCFCE7' : (item.status === 'Rejected' ? '#FEE2E2' : '#FEF3C7');

                    // Add Image Link
                    const proofLink = item.image
                        ? `<br><a href="${item.image}" target="_blank" style="color:#2563EB; text-decoration:none; font-size:10px;">[View Receipt]</a>`
                        : '';

                    div.innerHTML = `
                            <div style="color:#666;">${item.date}</div>
                            <div>
                                <div style="font-weight:600; color:#333;">${item.category}</div>
                                <div style="color:#888; font-size:10px;">${item.description || ''} ${proofLink}</div>
                            </div>
                            <div style="text-align:right; font-weight:600;">ر.س${item.amount}</div>
                            <div style="text-align:right;">
                                <span style="padding:2px 6px; border-radius:4px; font-size:10px; background:${statusBg}; color:${statusColor}; font-weight:bold;">
                                    ${item.status}
                                </span>
                            </div>
                        `;
                    listContainer.appendChild(div);
                });
            }

            // 3. Generate (Native Print for Clickable Links)
            const element = document.getElementById('pdf-template');
            // Note: display:block is handled by @media print CSS, 
            // but we populate the data in the DOM.

            // Add a temporary class to body to force print mode if needed? 
            // No, @media print handles visibility.

            // We just need to ensure the element exists.

            // Trigger Print
            // Trigger Print with Class Toggle
            document.body.classList.add('printing-report');
            setTimeout(() => {
                window.print();
                document.body.classList.remove('printing-report');
            }, 100);

            // Reset Button
            btn.textContent = oldText;
            btn.disabled = false;
            this.showToast("Export initiated", "success");

        } catch (e) {
            console.error(e);
            btn.textContent = oldText;
            btn.disabled = false;
            this.showToast("Export Error: " + e.message, "error");
        }
    },

    /* --- ADMIN DASHBOARD --- */

    switchAdminTab: function (status) {
        this.state.adminFilters.status = status;

        // Update UI
        document.querySelectorAll('.tabs .nav-item').forEach(b => {
            b.classList.remove('active');
            b.style.background = '';
            b.style.color = '';
            b.style.border = '';
        });
        const activeBtn = document.getElementById('tab-' + status.toLowerCase());
        if (activeBtn) {
            activeBtn.classList.add('active');
            activeBtn.style.background = 'rgba(255,193,7,0.2)';
            activeBtn.style.color = '#FFC107';
            if (status === 'Approved') { activeBtn.style.color = '#10B981'; activeBtn.style.background = 'rgba(16,185,129,0.2)'; }
            if (status === 'Rejected') { activeBtn.style.color = '#EF4444'; activeBtn.style.background = 'rgba(239,68,68,0.2)'; }
            if (status === 'All') { activeBtn.style.color = '#6B7280'; activeBtn.style.background = 'rgba(107,114,128,0.2)'; }
        }

        const title = document.getElementById('admin-list-title');
        title.textContent = status === 'All' ? 'All History' : status + ' Requests';

        this.loadAdminDashboard();
    },


    loadDriverList: function () {
        const sel = document.getElementById('admin-filter-driver');
        if (sel.options.length > 1) return; // Already loaded

        sel.innerHTML = '<option value="All">Loading...</option>';
        google.script.run.withSuccessHandler(drivers => {
            sel.innerHTML = '<option value="All">All Drivers</option>';
            drivers.forEach(d => {
                const opt = document.createElement('option');
                opt.value = d.id;
                opt.textContent = `${d.name} (${d.id})`;
                sel.appendChild(opt);
            });
        }).getDriverList();
    },
    loadAdminDashboard: function () {
        // init state if missing
        if (!this.state.adminFilters) this.state.adminFilters = { status: 'Pending', driverId: 'All' };

        // Update filter object from UI
        const driverSel = document.getElementById('admin-filter-driver');
        if (driverSel) this.state.adminFilters.driverId = driverSel.value;

        // Initial Driver Load
        this.loadDriverList();

        const listContainer = document.getElementById('admin-list-container');
        const totalEl = document.getElementById('admin-total-spent');
        const pendingEl = document.getElementById('admin-pending-count');

        // New Stats Elements
        const effEl = document.getElementById('admin-stat-eff');
        const bestEl = document.getElementById('admin-stat-best');

        listContainer.innerHTML = '<div class="center" style="opacity:0.6;">Loading...</div>';

        google.script.run
            .withSuccessHandler((data) => {
                console.log("Admin Data:", data);
                if (data.success) {
                    // Apply Currency
                    if (data.settings && data.settings.currency) {
                        this.state.currencySymbol = data.settings.currency;
                        const currSelect = document.getElementById('admin-currency-select');
                        if (currSelect) currSelect.value = data.settings.currency;
                    }

                    // Store full data for analytics
                    this.state.adminDashboardData = data.expenseList;

                    // Fuel price fetching from UI removed - fetching from sheet B1 only

                    const symbol = this.state.currencySymbol || '₹';

                    totalEl.textContent = symbol + (data.stats.total || 0).toLocaleString();
                    pendingEl.textContent = data.stats.count || 0; // View Count currently

                    // Render Advanced Stats
                    if (effEl) effEl.textContent = symbol + (data.stats.avgCostKm || 0).toFixed(2) + '/km';
                    if (bestEl) bestEl.textContent = data.stats.bestDriver || 'N/A';

                    // Update Label based on context (Pending vs Records)
                    // If status is Pending, count represents Pending. Else it represents "Records"
                    const label = pendingEl.previousElementSibling;
                    if (label) label.textContent = this.state.adminFilters.status === 'Pending' ? 'Pending' : 'Records';

                    listContainer.innerHTML = '';
                    if (data.expenseList.length === 0) {
                        listContainer.innerHTML = '<div class="center" style="padding:20px; opacity:0.6;">No records found.</div>';
                        return;
                    }

                    data.expenseList.forEach(item => {
                        const card = document.createElement('div');
                        card.className = 'card';

                        // Proof Link
                        const proof = item.image
                            ? `<a href="${item.image}" target="_blank" style="float:right; text-decoration:none; font-size:16px;">🖼️</a>`
                            : '';


                        // Checkbox Logic (Only for Pending)
                        let checkboxHtml = '';
                        if (item.status === 'Pending') {
                            checkboxHtml = `
                                <div style="margin-right:12px; display:flex; align-items:center;">
                                    <input type="checkbox" class="bulk-checkbox" onchange="app.toggleSelection('${item.txnId}', this.checked)">
                                </div>`;
                        }

                        // Action Buttons
                        let actions = '';
                        if (item.status === 'Pending') {
                            actions = `
                                <div style="display:flex; gap:8px; margin-top:12px;">
                                    <button class="btn" style="background:#10B981; font-size:12px; padding:8px;" onclick="app.handleApproval('${item.txnId}', 'Approved')">Approve</button>
                                    <button class="btn" style="background:#EF4444; font-size:12px; padding:8px;" onclick="app.handleApproval('${item.txnId}', 'Rejected')">Reject</button>
                                    <button class="btn-secondary" style="font-size:12px; padding:8px;" onclick="app.editExpense('${item.txnId}')">✏️ Edit</button>
                                </div>`;
                            card.style.borderLeft = "4px solid #F59E0B";
                        } else {
                            const badgeColor = item.status === 'Approved' ? '#10B981' : '#EF4444';

                            // REJECTION REVERSAL LOGIC
                            let extraBtn = '';
                            if (item.status === 'Rejected') {
                                extraBtn = `<button class="btn-secondary" style="font-size:10px; padding:4px 8px; margin-right:8px; color:#10B981; border-color:#10B981;" onclick="app.handleApproval('${item.txnId}', 'Approved')">♻️ Re-Approve</button>`;
                            }

                            actions = `
                                <div style="margin-top:8px; display:flex; justify-content:space-between; align-items:center;">
                                    <span style="color:${badgeColor}; font-weight:bold; font-size:12px;">${item.status}</span>
                                    <div>
                                        ${extraBtn}
                                        <button class="btn-secondary" style="font-size:10px; padding:4px 8px;" onclick="app.editExpense('${item.txnId}')">✏️ Edit</button>
                                    </div>
                                </div>`;
                            card.style.borderLeft = item.status === 'Approved' ? "4px solid #10B981" : "4px solid #EF4444";
                        }

                        card.innerHTML = `
                                <div style="display:flex; align-items:flex-start;">
                                    ${checkboxHtml}
                                    <div style="flex:1;">
                                        <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                                            <div style="flex:1;">
                                                <div style="font-size:10px; color:var(--text-secondary);">${item.date} • ${item.driverId}</div>
                                                <div style="font-weight:600; font-size:14px; margin-top:2px;">${item.category}</div>
                                                <div style="font-size:12px; opacity:0.8;">${item.description || ''} 
                                                    <span style="color:#2563EB; font-weight:500;">${item.displayKm ? '(' + item.displayKm + ')' : (item.km ? '(' + item.km + ' km)' : '')}</span>
                                                </div>
                                            </div>
                                            <div style="text-align:right; margin-left:8px;">
                                                <div style="font-weight:700; color:var(--primary-color);">${symbol}${item.amount}</div>
                                                ${proof}
                                            </div>
                                        </div>
                                        <div style="font-size:10px; color:#888; margin-top:4px;">Vehicle: ${item.vehicleId || 'N/A'}</div>
                                        ${actions}
                                    </div>
                                </div>
                            `;
                        listContainer.appendChild(card);
                    });

                    // Cache for editing
                    this.state.dashboardData = data.expenseList;

                } else {
                    alert("Error: " + data.message);
                }
            })
            .withFailureHandler(err => {
                listContainer.innerHTML = '<div class="center" style="color:red;">Failed to load.</div>';
            })
            .getAdminDashboardData(this.state.adminFilters);
    },

    handleApproval: function (txnId, status) {
        if (!confirm(`Are you sure you want to mark this as ${status}?`)) return;

        // Optimistic UI - Find card and dim it
        // Actually, let's just reload for simplicity and safety

        google.script.run
            .withSuccessHandler((res) => {
                if (res.success) {
                    this.showToast(`Expense ${status}`, 'success');
                    this.loadAdminDashboard(); // Build fresh list
                } else {
                    this.showToast("Error: " + res.message, 'error');
                }
            })
            .withFailureHandler(err => this.showToast("Server Error: " + err, 'error'))
            .updateExpenseStatus(txnId, status);
    },

    /* --- DRIVER MANAGEMENT --- */
    showManageDrivers: function () {
        this.showView('admin-drivers-view');
        this.loadDriverTable();
    },

    showAdminHome: function () {
        this.showView('admin-view');
    },

    loadDriverTable: function () {
        const container = document.getElementById('driver-list-container');
        container.innerHTML = '<div class="center" style="opacity:0.6;">Loading drivers...</div>';

        google.script.run.withSuccessHandler(res => {
            if (!res.success) {
                container.innerHTML = `<div style="color:red">Error: ${res.message}</div>`;
                return;
            }

            container.innerHTML = '';
            if (res.drivers.length === 0) {
                container.innerHTML = '<div class="center" style="opacity:0.6;">No drivers found.</div>';
                return;
            }

            res.drivers.forEach(d => {
                const card = document.createElement('div');
                card.className = 'card';
                card.innerHTML = `
                        <div style="display:flex; justify-content:space-between; align-items:center;">
                            <div>
                                <div style="font-weight:bold; font-size:14px;">${d.name}</div>
                                <div style="font-size:12px; color:#666;">${d.driverId} • ${d.phone}</div>
                                <div style="font-size:11px; opacity:0.8; margin-top:2px;">${d.vehicleId || 'No Vehicle'}</div>
                            </div>
                            <button class="btn-secondary" style="color:#EF4444; border:1px solid #EF4444; font-size:11px; padding:6px;" onclick="app.deleteDriver('${d.driverId}')">Delete</button>
                        </div>
                    `;
                container.appendChild(card);
            });
        }).manageDrivers('GET', null);
    },

    openDriverModal: function (mode) {
        document.getElementById('driver-modal').classList.remove('hidden');
        document.getElementById('drv-id').value = '';
        document.getElementById('drv-name').value = '';
        document.getElementById('drv-phone').value = '';
        document.getElementById('drv-pin').value = '';
        document.getElementById('drv-vehicle').value = '';
    },

    closeDriverModal: function () {
        document.getElementById('driver-modal').classList.add('hidden');
    },

    saveDriver: function () {
        const data = {
            driverId: document.getElementById('drv-id').value.toUpperCase(),
            name: document.getElementById('drv-name').value,
            phone: document.getElementById('drv-phone').value,
            pin: document.getElementById('drv-pin').value,
            vehicleId: document.getElementById('drv-vehicle').value
        };

        const btn = document.querySelector('#driver-modal button[type="submit"]');
        btn.textContent = "Saving...";
        btn.disabled = true;

        google.script.run.withSuccessHandler(res => {
            btn.textContent = "Save Driver";
            btn.disabled = false;
            if (res.success) {
                this.showToast("Driver Added!", "success");
                this.closeDriverModal();
                this.loadDriverTable();
            } else {
                this.showToast("Error: " + res.message, "error");
            }
        }).manageDrivers('ADD', data);
    },

    /* --- ADVANCED ANALYTICS --- */
    showAnalytics: function () {
        this.showView('analytics-view');
        this.loadAnalytics();
    },

    toggleAnalyticsView: function () {
        const val = document.getElementById('ana-chart-toggle').value;
        document.getElementById('cat-chart-container').classList.toggle('hidden', val !== 'cat');
        document.getElementById('trend-chart-container').classList.toggle('hidden', val !== 'trend');
    },

    loadAnalytics: function () {
        try {
            // Ensure currency is set
            this.state.currencySymbol = 'ر.س';

            // If no data, try to fetch or wait
            if (!this.state.adminDashboardData) {
                this.showToast("Loading data for analysis...", "info");
                this.loadAdminDashboard(); // This will trigger dashboard load if it hasn't already
                return;
            }

            const data = this.state.adminDashboardData.filter(x => x.status === 'Approved');
            if (data.length === 0) {
                this.showToast("No approved data for analytics", "info");
                return;
            }

            // 1. Populate Filter Dropdowns (Once)
            const filterDriver = document.getElementById('ana-filter-driver');
            const filterMonth = document.getElementById('ana-filter-month');

            if (filterDriver && filterDriver.options.length === 1) {
                const uniqueDrivers = [...new Set(data.map(x => x.driverId))].sort();
                uniqueDrivers.forEach(d => {
                    const opt = document.createElement('option');
                    opt.value = opt.textContent = d;
                    filterDriver.appendChild(opt);
                });
            }
            if (filterMonth && filterMonth.options.length === 1) {
                const uniqueMonths = [...new Set(data.map(x => {
                    if (!x.date || !x.date.includes('/')) return null;
                    const p = x.date.split('/');
                    return p[1] + '/' + p[2];
                }).filter(Boolean))].sort((a, b) => {
                    const [m1, y1] = a.split('/'); const [m2, y2] = b.split('/');
                    return new Date(y1, m1 - 1) - new Date(y2, m2 - 1);
                });
                uniqueMonths.forEach(m => {
                    const opt = document.createElement('option');
                    opt.value = opt.textContent = m;
                    filterMonth.appendChild(opt);
                });
            }

            // 2. Apply Filters
            const selectedDriver = filterDriver.value;
            const selectedMonth = filterMonth.value;

            const filtered = data.filter(x => {
                const dMatch = selectedDriver === 'All' || x.driverId === selectedDriver;
                let mMatch = selectedMonth === 'All';
                if (!mMatch && x.date && x.date.includes('/')) {
                    const p = x.date.split('/');
                    mMatch = (p[1] + '/' + p[2]) === selectedMonth;
                }
                return dMatch && mMatch;
            });

            // 3. KPI Containers
            const volEl = document.getElementById('ana-total-vol');
            const effEl = document.getElementById('ana-avg-eff');
            const cpkEl = document.getElementById('ana-cpk');
            const fuelShareEl = document.getElementById('ana-fuel-share');
            const fuelContainer = document.getElementById('fuel-insights-container');
            const catCanvas = document.getElementById('categoryChart');
            const trendCanvas = document.getElementById('trendChart');
            const compCanvas = document.getElementById('comparisonChart');

            if (!catCanvas || !trendCanvas || !compCanvas) return;

            // 4. Data Processing
            let totalAmt = 0;
            let fuelAmt = 0;
            let totalKm = 0;
            let totalLiters = 0;
            const catTotals = {};
            const trendData = {};
            const driverStats = {};

            filtered.forEach(x => {
                const amt = parseFloat(x.amount || 0);
                totalAmt += amt;

                // Category
                const cat = x.category || 'Other';
                catTotals[cat] = (catTotals[cat] || 0) + amt;
                if (cat === 'Fuel') fuelAmt += amt;

                if (x.date && x.date.includes('/')) {
                    const p = x.date.split('/');
                    const key = p[1] + '/' + p[2];
                    trendData[key] = (trendData[key] || 0) + amt;
                }

                // Driver Analysis
                const dId = x.driverId || 'Unknown';
                if (!driverStats[dId]) driverStats[dId] = { total: 0, km: 0, liters: 0, count: 0 };
                driverStats[dId].total += amt;

                if (x.category === 'Fuel') {
                    const l = parseFloat(x.liters || 0);
                    const k = parseFloat(x.delta || 0);
                    driverStats[dId].liters += l;
                    driverStats[dId].km += k;
                    totalLiters += l;
                    totalKm += k;
                    driverStats[dId].count++;
                }
            });

            // 5. Update KPI Cards
            volEl.textContent = 'ر.س' + totalAmt.toLocaleString();

            const avgEff = totalKm > 0 ? (totalLiters / totalKm * 100).toFixed(1) : '0.0';
            effEl.textContent = `${avgEff} L/100`;

            const cpk = totalKm > 0 ? (totalAmt / totalKm).toFixed(2) : '0.00';
            cpkEl.textContent = 'ر.س' + cpk;

            const fuelShare = totalAmt > 0 ? Math.round((fuelAmt / totalAmt) * 100) : 0;
            fuelShareEl.textContent = `${fuelShare}%`;

            // 6. Charts Rendering
            if (this.state.charts?.cat) this.state.charts.cat.destroy();
            if (this.state.charts?.trend) this.state.charts.trend.destroy();
            if (this.state.charts?.comp) this.state.charts.comp.destroy();
            if (!this.state.charts) this.state.charts = {};

            const chartDefaults = {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { labels: { color: '#94A3B8', font: { size: 10 } } }
                },
                scales: {
                    y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94A3B8', font: { size: 10 } } },
                    x: { grid: { display: false }, ticks: { color: '#94A3B8', font: { size: 10 } } }
                }
            };

            this.state.charts.cat = new Chart(catCanvas.getContext('2d'), {
                type: 'doughnut',
                data: {
                    labels: Object.keys(catTotals),
                    datasets: [{
                        data: Object.values(catTotals),
                        backgroundColor: ['#6366F1', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#06B6D4']
                    }]
                },
                options: {
                    ...chartDefaults,
                    plugins: { legend: { position: 'bottom', labels: chartDefaults.plugins.legend.labels } },
                    scales: {}
                }
            });

            const sortedMonths = Object.keys(trendData).sort((a, b) => {
                const [m1, y1] = a.split('/'); const [m2, y2] = b.split('/');
                return new Date(y1, m1 - 1) - new Date(y2, m2 - 1);
            });
            this.state.charts.trend = new Chart(trendCanvas.getContext('2d'), {
                type: 'line',
                data: {
                    labels: sortedMonths,
                    datasets: [{
                        label: 'Volume',
                        data: sortedMonths.map(m => trendData[m]),
                        borderColor: '#6366F1',
                        backgroundColor: 'rgba(99, 102, 241, 0.1)',
                        fill: true,
                        tension: 0.4
                    }]
                },
                options: chartDefaults
            });

            const dLabels = Object.keys(driverStats);
            this.state.charts.comp = new Chart(compCanvas.getContext('2d'), {
                type: 'bar',
                data: {
                    labels: dLabels,
                    datasets: [
                        { label: 'Total Spending', data: dLabels.map(l => driverStats[l].total), backgroundColor: '#6366F1', borderRadius: 6 },
                        { label: 'KM Covered', data: dLabels.map(l => driverStats[l].km), backgroundColor: '#10B981', borderRadius: 6 }
                    ]
                },
                options: chartDefaults
            });

            // 7. Rankings Leaderboard
            fuelContainer.innerHTML = '';
            const ranked = Object.keys(driverStats)
                .filter(d => driverStats[d].km > 0)
                .map(d => ({
                    id: d,
                    eff: (driverStats[d].liters / driverStats[d].km * 100),
                    km: driverStats[d].km
                }))
                .sort((a, b) => a.eff - b.eff);

            if (ranked.length === 0) {
                fuelContainer.innerHTML = '<div class="center" style="font-size:12px; opacity:0.6; padding:20px;">No mileage data available</div>';
            } else {
                ranked.forEach((d, i) => {
                    const badge = i === 0 ? '🏆' : (i === 1 ? '🥇' : (i === 2 ? '🥈' : (i === 3 ? '🥉' : `#${i + 1}`)));
                    const div = document.createElement('div');
                    div.className = 'summ-row';
                    div.style.padding = '12px';
                    div.style.background = i === 0 ? 'rgba(245, 158, 11, 0.08)' : 'rgba(255,255,255,0.02)';
                    div.style.borderRadius = '12px';
                    div.style.marginBottom = '6px';
                    div.innerHTML = `
                            <div style="display:flex; align-items:center; gap:12px;">
                                <div style="font-size:18px;">${badge}</div>
                                <div>
                                    <div style="font-weight:600; font-size:13px; color:var(--text-primary);">${d.id}</div>
                                    <div style="font-size:10px; color:var(--text-secondary);">${d.km.toLocaleString()} KM covered</div>
                                </div>
                            </div>
                            <div style="text-align:right;">
                                <div style="font-weight:bold; color:${i === 0 ? 'var(--warning-color)' : 'var(--primary-color)'}; font-size:14px;">
                                    ${d.eff.toFixed(1)} <span style="font-size:9px; opacity:0.7;">L/100</span>
                                </div>
                            </div>
                        `;
                    fuelContainer.appendChild(div);
                });
            }
        } catch (err) {
            console.error("Analytics Error:", err);
            this.showToast("Analysis error - see console", "error");
        }
    },

    // saveFuelPrice removed - fetch from sheet B1 only

    deleteDriver: function (id) {
        if (!confirm(`Delete driver ${id}? This cannot be undone.`)) return;

        google.script.run.withSuccessHandler(res => {
            if (res.success) {
                this.showToast("Driver Deleted", "success");
                this.loadDriverTable();
            } else {
                this.showToast("Error: " + res.message, "error");
            }
        }).manageDrivers('DELETE', { driverId: id });
    },

    printAnalyticsReport: function () {
        document.body.classList.add('printing-analytics');
        // Ensure charts are rendered
        this.loadAnalytics();
        window.print();
        document.body.classList.remove('printing-analytics');
    },

    /* --- ADMIN REPORTS --- */
    printAdminReport: function () {
        // Reuse the PDF template logic but populate with ADMIN DATA
        try {
            // 1. Prepare Data
            const data = this.state.dashboardData || []; // Currently loaded filtered list
            const filters = this.state.adminFilters || {};

            // 2. Populate Template
            const driverLabel = filters.driverId === 'All' ? 'All Drivers' : filters.driverId;
            const statusLabel = filters.status;

            document.getElementById('pdf-driver-name').textContent = `${driverLabel} (${statusLabel})`;
            document.getElementById('pdf-period').textContent = `Generated Report`;
            document.getElementById('pdf-gen-date').textContent = new Date().toLocaleDateString();

            // Totals
            let total = 0;
            let km = 0;
            data.forEach(x => {
                total += parseFloat(x.amount || 0);
                km += parseFloat(x.km || 0);
            });

            document.getElementById('pdf-total-amt').textContent = 'ر.س' + total.toFixed(2);
            document.getElementById('pdf-total-km').textContent = km.toLocaleString() + ' KM';
            document.getElementById('pdf-total-trips').textContent = data.length;

            // List
            const listContainer = document.getElementById('pdf-list-container');
            listContainer.innerHTML = '';

            if (data.length === 0) {
                listContainer.innerHTML = '<div style="padding:20px; text-align:center;">No records.</div>';
            }

            data.forEach(item => {
                const div = document.createElement('div');
                div.style.cssText = "display:grid; grid-template-columns: 2fr 3fr 2fr 2fr; padding:12px 15px; border-bottom:1px solid #eee; font-size:12px; align-items:center;";

                const statusColor = item.status === 'Approved' ? '#166534' : (item.status === 'Rejected' ? '#991B1B' : '#92400E');
                const statusBg = item.status === 'Approved' ? '#DCFCE7' : (item.status === 'Rejected' ? '#FEE2E2' : '#FEF3C7');

                // Add Image Link
                const proofLink = item.image
                    ? `<br><a href="${item.image}" target="_blank" style="color:#2563EB; text-decoration:none; font-size:10px;">[View Receipt]</a>`
                    : '';

                div.innerHTML = `
                         <div style="color:#666;">${item.date}</div>
                         <div>
                             <div style="font-weight:600; color:#333;">${item.category}</div>
                             <div style="color:#888; font-size:10px;">${item.driverId} - ${item.description || ''} ${proofLink}</div>
                         </div>
                         <div style="text-align:right; font-weight:600;">ر.س${item.amount}</div>
                         <div style="text-align:right;">
                             <span style="padding:2px 6px; border-radius:4px; font-size:10px; background:${statusBg}; color:${statusColor}; font-weight:bold;">
                                 ${item.status}
                             </span>
                         </div>
                     `;
                listContainer.appendChild(div);
            });

            document.body.classList.add('printing-report');
            window.print();
            document.body.classList.remove('printing-report');

        } catch (e) {
            console.error(e);
            alert("Report Error: " + e.message);
        }
    },
    toggleFields: function () {
        const cat = document.getElementById('expense-category').value;
        const descGroup = document.getElementById('desc-group');
        const descInput = document.getElementById('expense-desc');

        if (cat === 'Other') {
            descGroup.classList.remove('hidden');
            descInput.required = true;
        } else {
            descGroup.classList.add('hidden');
            descInput.required = false;
            descInput.value = '';
        }
    },

    runSystemDebug: function () {
        const toast = document.getElementById('toast');
        toast.textContent = "Running Diagnostics...";
        toast.className = 'show';

        google.script.run
            .withSuccessHandler((res) => {
                const msg = `
    SHEET DIAGNOSIS:
    Sheet Found: ${res.foundExpensesSheet}
    Sheet Name Config: ${res.expensesSheetName}
    All Sheets: ${res.allSheets.join(', ')}

    HEADERS (Row 1):
    ${res.headers.join(' | ')}

    FIRST ROW DATA (Row 2):
    ${res.firstRow.join(' | ')}
                    `;
                alert(msg);
                console.log(msg);
            })
            .getDebugInfo();
    },

    /* BULK ACTIONS */

    /* BULK ACTIONS */
    selectedTxns: new Set(),

    toggleSelection: function (txnId, isChecked) {
        if (isChecked) {
            this.selectedTxns.add(txnId);
        } else {
            this.selectedTxns.delete(txnId);
        }
        this.updateBulkUI();
    },

    updateBulkUI: function () {
        const count = this.selectedTxns.size;
        const bar = document.getElementById('bulk-bar');
        document.getElementById('bulk-count').textContent = count + " Selected";

        if (count > 0) {
            bar.classList.add('visible');
        } else {
            bar.classList.remove('visible');
        }
    },

    executeBulkAction: function (status) {
        const count = this.selectedTxns.size;
        if (count === 0) return;

        if (!confirm(`Are you sure you want to mark ${count} items as ${status}?`)) return;

        const txns = Array.from(this.selectedTxns);

        // Optimistic UI - Hide Bar
        document.getElementById('bulk-bar').classList.remove('visible');

        google.script.run
            .withSuccessHandler((res) => {
                if (res.success) {
                    this.showToast(`Successfully ${status} ${res.count} items.`, 'success');
                    this.selectedTxns.clear();
                    this.updateBulkUI();
                    this.loadAdminDashboard(); // Reload
                } else {
                    this.showToast("Bulk Update Failed.", "error");
                }
            })
            .withFailureHandler(err => {
                this.showToast("Error: " + err, "error");
            })
            .updateExpenseStatusBulk(txns, status);
    },

    /* THEME TOGGLE */


    /* THEME TOGGLE */
    toggleTheme: function () {
        const body = document.body;
        body.classList.toggle('light-mode');
        const isLight = body.classList.contains('light-mode');
        localStorage.setItem('theme', isLight ? 'light' : 'dark');
    },

    /* INSTALL & CURRENCY */

    showInstallGuide: function () {
        document.getElementById('install-modal').style.display = 'flex';
    },

    initCurrency: function () {
        // Fetch from backend or wait for admin load
        if (this.state.isAdminMode) {
            // Admin load will fetch it
        } else {
            // Try to guess or default. Ideally we fetch public settings here.
            // For now, let's just make sure loadAdminDashboard fetches it.
        }
    },

    changeCurrency: function () {
        const select = document.getElementById('admin-currency-select');
        const newCurrency = select.value;
        this.state.currencySymbol = newCurrency;

        // Save to Backend
        google.script.run
            .withSuccessHandler((res) => {
                if (res.success) {
                    this.showToast("Currency Updated to " + newCurrency, "success");
                    this.loadAdminDashboard(); // Refresh all views
                }
            })
            .saveAppSettings({ currency: newCurrency });
    },

    initTheme: function () {
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme === 'light') {
            document.body.classList.add('light-mode');
        }
    },

    showToast: function (message, type) {
        const toast = document.getElementById('toast');

        // Hard Reset
        if (this.state.toastTimer) clearTimeout(this.state.toastTimer);
        toast.classList.remove('show');
        void toast.offsetWidth; // Force Reflow

        toast.textContent = message;
        toast.className = (type === 'error' ? 'error' : 'success') + ' show';

        this.state.toastTimer = setTimeout(() => {
            toast.classList.remove('show');
        }, 4000); // 4s as requested
    }
};

// Initialize
window.onload = function () {
    app.init();
};
